### ISSUE TITLE
Feature Add : Version Argument

### ISSUE THREAD

**Issue by joelazwar** [abuZayed15/check-link#11]
Hi, I'm interested in contributing to your code for lab 2, I wanted to try my handout in C# programming and your program seemed like a good fit for it.

I've noticed that you currently dont have a feature for a v argument to check for the version so I wanted to add minor feature for it that adds that functionality. I'm also thinking of adding another feature that might be more significant as well but for now I thought I would try something small first.

**Comment by ceterisp** [comment]
Hey @joelazwar , thank you for your interest in my project! Unfortunately, I already have -v and --version already working for my project
![image](https://user-images.githubusercontent.com/36981880/94831695-05811980-03db-11eb-9dbc-84e4644a309a.png)

But I forgot to mention that in the README.md which was why you thought it didn't exist. The features I currently have are:

- All the required features
- Returning status codes other than the ones that were required from us.
- Reading just a website link
- version arguments
- Passing multiple files as arguments 

 Is there any other feature you had in mind that you wanted to add? I am open to suggestions 👍
