### ISSUE TITLE
File doesn't exist message missing

### ISSUE THREAD

**Issue by yuanLeeMidori** [abuZayed15/check-link#8]
When I use a random character with the tool, it looks like the tool does read the file and report it with 0 good or bad URLs. However, I believe it should display a message such as "file doesn't exist" or "invalid input".

![fileNotExist](https://user-images.githubusercontent.com/50813726/94219359-a724da00-feb4-11ea-92e1-7cb895a39f4f.PNG)

**Comment by ceterisp** [comment]
Thank you for creating this issue! My PR(https://github.com/abuZayed15/check-link/pull/10) has resolved this problem. 

![image](https://user-images.githubusercontent.com/36981880/94229169-cdef0a80-fecc-11ea-9430-162d5f50e219.png)
